name = input('enter your name')
age = input('enter your age')
dob = input('enter your dob')
print('name: ',name)
print('age: ',age)
print('dob: ',dob)
email = input('enter your email')
number = input('enter your number')
address = ('enter your address')
print('email: ',email)
print('number:',number)
print('address:',address)